In [1]:
import numpy as np

In [2]:
wk = np.arange(15)
wk

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [7]:
wk = wk.reshape((3,5))
wk

array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])

In [8]:
wk.T

array([[ 0, 5, 10],
 [ 1, 6, 11],
 [ 2, 7, 12],
 [ 3, 8, 13],
 [ 4, 9, 14]])

In [9]:
arr = np.random.randn(6,3)
arr

array([[ 0.4731578 , -0.17319332, -0.18303576],
 [-0.07491194, -0.1669601 , -0.19852512],
 [-0.67199167, -0.7472552 , -0.33324893],
 [-0.82255503, -0.30925031, -1.31459746],
 [ 0.01396715, 0.47930752, -1.48391001],
 [ 1.09634336, -0.97932706, -1.18915132]])

In [10]:
los = np.random.randint(10,20,size=12)
los

array([18, 15, 15, 17, 16, 11, 16, 10, 19, 14, 13, 15])

In [11]:
macierz = np.random.randint(8,42,size=(5,4))
macierz

array([[27, 32, 21, 27],
 [25, 9, 37, 41],
 [ 8, 26, 9, 40],
 [35, 18, 32, 18],
 [25, 9, 33, 14]])

In [12]:
float_macierz = np.random.uniform(2.2,12.8,size=(3,7))
float_macierz

array([[10.22015311, 11.14724157, 11.52781983, 5.49210415, 11.43897023,
 3.97526357, 5.75810786],
 [ 2.53437778, 9.88247589, 10.35494105, 6.6347816 , 10.94476837,
 11.59340027, 5.59384924],
 [ 4.32880206, 2.32162926, 4.30168686, 3.64394245, 11.18638873,
 3.05375842, 4.46246815]])

In [13]:
#tensor 3D
tens = np.arange(27).reshape(3,3,3)
tens

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
teserakt = np.random.randint(17,121,size=(3,4,5,7))
teserakt

array([[[[ 62,  84, 105, 101, 100,  76, 100],
         [ 83,  41,  61, 108, 113,  62,  82],
         [ 53, 119,  51,  59,  56,  34,  74],
         [ 84,  92,  57,  27,  96,  35,  99],
         [ 20,  66,  88,  20,  44, 104,  49]],

        [[103,  88,  72,  52,  39,  73, 120],
         [ 90,  60,  97,  85,  63,  77, 101],
         [ 55,  91,  64,  60, 104, 110, 104],
         [ 55,  33,  80,  34, 110,  76,  21],
         [119,  38,  81,  48,  94,  38,  29]],

        [[ 47,  56, 113,  22,  51, 114,  35],
         [ 82, 113,  56, 115,  27,  75,  39],
         [107,  56,  34,  18,  51,  17,  70],
         [ 38,  41,  36,  58,  64,  27,  61],
         [ 81,  23,  41,  37,  53,  77, 111]],

        [[ 33,  68,  54, 111,  70,  40,  17],
         [ 29,  22,  24,  43,  83,  84, 113],
         [100,  73,  51,  71,  57,  62,  40],
         [ 39,  48, 106,  45, 108, 105, 111],
         [ 22, 101,  79,  89,  56,  38,  26]]],


       [[[120,  92,  79,  49,  82,  49,  60],
         [ 44, 118,  56,