In [1]:
import numpy as np

In [2]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.empty(10)

array([4.74460749e-310, 0.00000000e+000, 2.46151512e-312, 2.33419537e-312,
 2.31297541e-312, 2.56761491e-312, 2.05833592e-312, 6.79038654e-313,
 2.37663529e-312, 0.00000000e+000])

In [6]:
u = np.arange(1,98,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [7]:
k = np.array([6,2,6,2,8,3,78,9,9,5,4,65,5])
k

array([ 6, 2, 6, 2, 8, 3, 78, 9, 9, 5, 4, 65, 5])

In [10]:
lista = [56,35,8.5,2.43,74,9,3,-65,2,-6,0]
print(lista)
print(type(lista))

[56, 35, 8.5, 2.43, 74, 9, 3, -65, 2, -6, 0]
<class 'list'>


In [11]:
nlista = np.array(lista)
print(nlista)
print(type(nlista))

[ 56.    35.     8.5    2.43  74.     9.     3.   -65.     2.    -6.
   0.  ]
<class 'numpy.ndarray'>


In [13]:
np.append(nlista,89)

array([ 56. , 35. , 8.5 , 2.43, 74. , 9. , 3. , -65. ,
 2. , -6. , 0. , 89. ])

In [14]:
np.insert(nlista,1,101)

array([ 56. , 101. , 35. , 8.5 , 2.43, 74. , 9. , 3. ,
 -65. , 2. , -6. , 0. ])

In [21]:
nlista = np.sort(nlista)

In [22]:
nlista[::-1]

array([ 74. , 56. , 35. , 9. , 8.5 , 3. , 2.43, 2. ,
 0. , -6. , -65. ])

In [16]:
m = np.linspace(0,25,num=9)
m

array([ 0. , 3.125, 6.25 , 9.375, 12.5 , 15.625, 18.75 , 21.875,
 25. ])

In [23]:
#konkatenacja list
l1 = [2,4,6,8]
l2 = [87,1,1,1]
l3 = [5,12,8,90]

In [24]:
l = l1+l2+l3
l

[2, 4, 6, 8, 87, 1, 1, 1, 5, 12, 8, 90]

In [25]:
np1 = np.array(l1)
np2= np.array(l2)
np3 = np.array(l3)

In [27]:
npkon = np.concatenate((np1,np2,np3))
npkon

array([ 2, 4, 6, 8, 87, 1, 1, 1, 5, 12, 8, 90])

In [28]:
z1 = [[1,3],[8,4]]
z1

[[1, 3], [8, 4]]

In [29]:
z1[0][1]

3

In [31]:
# z1[0,1]
#nie można wypisywac elementów macierzowo [w,k]

In [32]:
tabnp = np.array(z1)
tabnp

array([[1, 3],
 [8, 4]])

In [33]:
tabnp[1][1]

4

In [34]:
tabnp[1,1]

4

In [35]:
#podstawowe operacje na macierzach
x = np.array([[2,8],[21,9]])
y = np.array([[15,6],[90,2]])

In [36]:
x

array([[ 2, 8],
 [21, 9]])

In [37]:
y

array([[15, 6],
 [90, 2]])

In [38]:
x+y

array([[ 17, 14],
 [111, 11]])

In [39]:
x-y

array([[-13, 2],
 [-69, 7]])

In [40]:
x*y

array([[ 30, 48],
 [1890, 18]])

In [41]:
x/y

array([[0.13333333, 1.33333333],
 [0.23333333, 4.5 ]])

In [42]:
x%2==0

array([[ True, True],
 [False, False]])

In [43]:
x*1.234

array([[ 2.468, 9.872],
 [25.914, 11.106]])

In [44]:
np.sin(x*np.pi*y)

array([[-1.07793678e-14, -5.87830464e-15],
 [ 3.15659661e-13, -2.20436424e-15]])

In [46]:
# import math
# math.sin(x*math.pi*y)

#korzystaj w z funkcji np a nie math!!!